### ISSUE TITLE
How to compute the composition of all predicted flow fields

### ISSUE THREAD

**Issue by Algolzw** [microsoft/Recursive-Cascaded-Networks#12]
Hello, I have a question that how to compute the composition of all predicted flow fields. Can I just use "SpatialTransformer(field1, field2)" to reconstruct the final displacement field?
Thanks.

**Comment by zsyzzsoft** [comment]
Suppose we have two displacement fields A and B, to compute A compose B, one should call SpatialTransformer(B, A) + A (see recursive_cascaded_networks.py, line 98-99).

**Comment by Algolzw** [comment]
May I ask why "+ A"? I'm really confused.

**Comment by zsyzzsoft** [comment]
It's because they are displacement fields. A detailed formula can be found in the VTN paper, section III.A.
