### ISSUE TITLE
Some problems encountered while running the GPU version

### ISSUE THREAD

**Issue by CGC1031** [microsoft/Recursive-Cascaded-Networks#13]
Dear author, 
I am a graduate student from suzhou, China. Thank you for your contributions.I was able to successfully implement your work on the CPU, but there was a problem running on the GPU that I couldn't solve.Based on the error, I guess there is something wrong with the versions of tensorflow and keras.
Could you tell me What versions of tensorflow/tensorflow-gpu/keras/cuda/cudnn/ is supported/expected? Sincerely looking forward to hearing from you soon.
My settings :python36,tensorflow=1.13.1,tensorflow-gpu=1.4.0,cuda=10.0,cudnn=7.4.1,keras=2.3.1, NVIDIA F=GeFroce RTX 2080 Ti，but it is faild.
ERRORS:
![QQ图片20200324215315](https://user-images.githubusercontent.com/53649087/77433935-08db8d00-6e1b-11ea-894d-06d1e8f81daf.png)
![QQ图片20200324215327](https://user-images.githubusercontent.com/53649087/77433950-0f6a0480-6e1b-11ea-8c2a-3721c497e2e8.png)

**Comment by zsyzzsoft** [comment]
Try to uninstall tensorflow 1.13.1 and tensorflow-gpu, and then reinstall tensorflow-gpu 1.4. Not sure whether the existence of a higher version of "tensorflow" causes the problem.

**Comment by CGC1031** [comment]
Thank you very much for your reply. I finally upgraded the tensorflow-gpu from 1.4.0 to 1.13.0, and finally succeeded.I hope this method can help others with the same problem.
