### ISSUE TITLE
about liver dataset

### ISSUE THREAD

**Issue by zzx332** [microsoft/Recursive-Cascaded-Networks#17]
Thanks for sharing your work in this field!
I have some questions about these words in the paper
"Raw scans are resampled  into 128 × 128 × 128 voxels after cropping unnecessary  area around the target object. For liver CT scans, a simple  threshold-based algorithm is applied to find a rough liver  bounding box for cropping."

1.What should I do to crop and resample？
Sorry I am not familar with image processing, what kind of tools should I use?
2.During training，how do I select two input image （fixed image and moving image）from dataset （e.g LiTs 130 CT scans，512x512x75）？
3.If I were to use a liver dataset, what preprocessing steps would I need to perform？

**Comment by zsyzzsoft** [comment]
If you use our provided datasets, there is nothing else to do --- they are already preprocessed. If you want to make your own dataset, a complete preprocessing pipeline for liver can be found in demo.py, which takes as input two raw CT scans for a forward pass.

**Comment by zzx332** [comment]
Thank you for your reply,i will check out demo.py.
I have another question.
How do I choose an image pair from mydataset for training，just random？

**Comment by zsyzzsoft** [comment]
You can prepocess them into a .h5 file like our provided dataset, then the training script would choose random image pairs for training by default.

**Comment by zzx332** [comment]
Thank you very much for your reply.
