### ISSUE TITLE
about VTN network structure

### ISSUE THREAD

**Issue by zzx332** [microsoft/Recursive-Cascaded-Networks#18]
hi,I have some questions about the code of VTN
```
        pred6 = convolve('pred6', conv6_1, dims, 3, 1)
        upsamp6to5 = upconvolve('upsamp6to5', pred6, dims, 4, 2, shape5[1:4])
        deconv5 = upconvolveLeakyReLU(
            'deconv5', conv6_1, shape5[4], 4, 2, shape5[1:4])
        concat5 = tf.concat([conv5_1, deconv5, upsamp6to5], 4, 'concat5')
```
in the VTN code,every upsampling part have pred,this structure is not mentioned in the paper.
what is the use of this operation?

**Comment by zsyzzsoft** [comment]
It would facilitate deep supervision but we didn't do it so I don't think it makes much difference. VTN should work without them.
