### ISSUE TITLE
KeyError: 'volume'

### ISSUE THREAD

**Issue by yangglebin** [microsoft/Recursive-Cascaded-Networks#2]
when I run:  python eval.py -c weights/VTN-10-liver -g 0
I got a error like:

File "C:\Users\Administrator\Desktop\Recursive-Cascaded-Networks\data_util\liver.py", line 163, in generator
ret['voxel1'][i, ..., 0], ret['voxel2'][i, ..., 0] = d1['volume'], d2['volume']
KeyError: 'volume'

who can solve this? Thx

**Comment by Shubham0209** [comment]
@yangglebin Can you please mention how to solve the issue? eval.py worked fine for me but when I run train.py I get the error mentioned by you. Please help!!
