### ISSUE TITLE
how to normalize CT scans by adjusting exposure so that the histograms of the images match each other

### ISSUE THREAD

**Issue by luckyxiaoqi** [microsoft/Recursive-Cascaded-Networks#20]
You wrote "normalize them by adjusting exposure so that the histograms of the images match each other" in the "Unsupervised 3D End-to-End Medical Image Registration with Volume Tweening Network". I want to know how to adjust exposure

**Comment by zsyzzsoft** [comment]
That is the old version. Now we only clip the intensity of the raw images within a certain range (e.g., [-25, 265] for liver) and then linearly rescale to [0, 255].

**Comment by luckyxiaoqi** [comment]
Thanks for your reply.
