### ISSUE TITLE
I used CHAOS CT liver dataset to get bad results

### ISSUE THREAD

**Issue by zzx332** [microsoft/Recursive-Cascaded-Networks#22]
The following is the data after processed.
train dataset is 35 ct. valid dataset is 5.
final dice score is 0.5 

Is there any problem? Is the intensity difference between the images too large?
I want to registration between ct and mr.What process should i do with mri image？

<img width="400" alt="微信截图_20200428171011" src="https://user-images.githubusercontent.com/45729525/80469477-3021fe80-8973-11ea-9806-ba29ef0996f0.png">

<img width="400" alt="微信截图_20200428165735" src="https://user-images.githubusercontent.com/45729525/80468253-87bf6a80-8971-11ea-8336-1a387084214d.png">

**Comment by zsyzzsoft** [comment]
This repo has not been tested for cross-modality registration purposes. However, if you want to do that, the first step should be normalizing two modalities (as well as train and val) into similar intensity distributions, or it would be bad results (because of the similarity loss).

**Comment by zzx332** [comment]
Thank you for your reply!
The auto_liver_mask preprocess in demo.py don't work on my ct dataset,can i crop area around the target object by manual？

**Comment by zsyzzsoft** [comment]
Yes, a rough crop is fine.

**Comment by zzx332** [comment]
In order to register MR to CT.I try to change similarloss to miloss(Mutual information).loss=-miloss+0.1reg_loss
Here is my result.(traindata:35ct,35mri,random combination).
Mi_loss:https://user-images.githubusercontent.com/45729525/81144615-08e8b400-8fa7-11ea-8c3e-e33d36cf8190.png
smooth_loss:https://user-images.githubusercontent.com/45729525/81144674-2584ec00-8fa7-11ea-9b95-d844c5842598.png
It looks like miloss is not converging.(decreases too much,from -0.02 to -0.35)
smooth_loss first decreases and then increases.
Here is dice on the test dataset.It looks ok, but the warped image is bad.
val_dice:https://user-images.githubusercontent.com/45729525/81145967-f58b1800-8fa9-11ea-88c4-2643784840e6.png
img_fixed:https://user-images.githubusercontent.com/45729525/81146587-2ddf2600-8fab-11ea-9aca-071f6256059e.jpg
img_moving:https://user-images.githubusercontent.com/45729525/81146583-2a4b9f00-8fab-11ea-962c-4ec433ff3cd6.jpg
img_warped:https://user-images.githubusercontent.com/45729525/81146166-531f6480-8faa-11ea-8130-bada6792eb4f.jpg
Is it caused by my loss function setting?

**Comment by zsyzzsoft** [comment]
This is actually an active research topic... So it is not surprising that some losses may or may not work for this setting.

**Comment by zzx332** [comment]
Ok thanks for your answers!
