### ISSUE TITLE
How to continue the training on the saved model?

### ISSUE THREAD

**Issue by CGC1031** [microsoft/Recursive-Cascaded-Networks#23]
According to my computer's hardware configuration, a full training session with 20,000 rounds takes a long time.How do you  build on the model that you trained before?For example, I have trained 10,000 rounds and saved them. How can I continue the training on the saved model?
Do you have any good Suggestions? Looking forward to your reply！

**Comment by zsyzzsoft** [comment]
Use the '-c' argument!

**Comment by CGC1031** [comment]
Thank you very much,this problem has been solved successfully.

**Comment by CGC1031** [comment]
May I ask what is the meaning of 'Total time'  and 'data' ? Looking forward to your reply.Thank you very much.
![QQ图片20200518222729](https://user-images.githubusercontent.com/53649087/82225233-84f3dc00-9957-11ea-8d21-5eb6c82d9d46.png)

**Comment by zsyzzsoft** [comment]
"Total time" is the measured time of a step; "data" is the percentage of data loading time over the "Total time", expected to be small.

**Comment by CGC1031** [comment]
Thank you for your reply , but I'm still a little confused.
As shown in the figure below , 200 steps take 2 minutes and 44 seconds , for a total of 164 seconds.  While "Total time"  is the measure time of one step equals 0.29 second , so 200*0.29 = 58 seconds . Why are the calculated times unequal ? 
![微信图片_20200520102110](https://user-images.githubusercontent.com/53649087/82398260-ff6e4a00-9a84-11ea-8c27-4e71c475b4e5.png)

**Comment by CGC1031** [comment]
This is picture.Thank you.
![QQ图片20200520103249](https://user-images.githubusercontent.com/53649087/82398406-5c6a0000-9a85-11ea-83fe-0f2a72bc6e54.png)

**Comment by zsyzzsoft** [comment]
This is only for monitoring purpose, and the "Total time" only measures the time of _some_ step. You may modify the code to get more accurate values.

**Comment by CGC1031** [comment]
OK，thank you very much.
