### ISSUE TITLE
About the .h5 files

### ISSUE THREAD

**Issue by henryhuangrui** [microsoft/Recursive-Cascaded-Networks#24]
Can the data format be 3d tiff?

**Comment by zsyzzsoft** [comment]
It needs some preprocessing. It would be fine if you can prepare your data into a single .h5 file.

**Comment by henryhuangrui** [comment]
> It needs some preprocessing. It would be fine if you can prepare your data into a single .h5 file.

I used hdfviewer to preview the h5 file you provided, but it failed.So, I wonder if the brain data you're providing is a whole sequence of slices, or just a set of pictures, which can make a big difference in registration results.it would be helpful if you could tell me how to preview your h5 data.

**Comment by zsyzzsoft** [comment]
It's a set of 3D images. Using h5py would be a good choice. You may look into the keys and visualize the images easily with Python.
