### ISSUE TITLE
my training result is not as good as paper

### ISSUE THREAD

**Issue by w19787** [microsoft/Recursive-Cascaded-Networks#28]
thanks for excellent paper and work. i try to re-train the project after migrating the project to tensorflow 2.0. Only api is migrated, no network, loss, structure, data preprocessing ,etc changed.

The following is the screen shot of training tensorboard on liver dataset:
![image](https://user-images.githubusercontent.com/731496/84463997-ec2a5500-aca5-11ea-9dfe-c1c2aeea08a6.png)
![image](https://user-images.githubusercontent.com/731496/84464014-f64c5380-aca5-11ea-86e0-b84d7fb43d94.png)

and the evalation result:
![image](https://user-images.githubusercontent.com/731496/84464064-154ae580-aca6-11ea-82e7-fb3d74d69f67.png)

any idea what might be go wrong? thanks.

**Comment by zsyzzsoft** [comment]
What setting are you running? I guess you are running the 1-cascade VTN version that should correspond to these numbers. Specify -n to train more cascades.

**Comment by w19787** [comment]
> What setting are you running? I guess you are running the 1-cascade VTN version that should correspond to these numbers. Specify -n to train more cascades.

thanks for reply. it is my bad not to notice the n should be changed for better performance according paper.

**Comment by w19787** [comment]
> What setting are you running? I guess you are running the 1-cascade VTN version that should correspond to these numbers. Specify -n to train more cascades.

in order to process the 10-cascade VTN training, what kinds of GPU is required? it is OOM on 16G v100 when train on 5 or 10 cascades.

**Comment by zsyzzsoft** [comment]
It would be fine if using 4 GPUs.

**Comment by w19787** [comment]
> It would be fine if using 4 GPUs.

after migrating to tf2.0 (since my server is installed new version's cuda which cannot run on tf1.4), the multi-gpu cannot work properly. the compute_gradients seems only work on gpu0. Currently, no idea how to fix it.
![image](https://user-images.githubusercontent.com/731496/84582770-d4c4a680-ae22-11ea-92fa-9b182d90a711.png)

![image](https://user-images.githubusercontent.com/731496/84582752-b068ca00-ae22-11ea-94fd-7a3acb03e1ee.png)

**Comment by w19787** [comment]
> It would be fine if using 4 GPUs.

@zsyzzsoft i have upload  https://github.com/w19787/Recursive-Cascaded-Networks-TF2.0, if you can advice how to fix the issue of multi-gpu support on this version will be appreciated!!!

**Comment by zsyzzsoft** [comment]
I haven't met this issue before and I'm not familiar with TF 2.0. Maybe the GPU specification doesn't work properly for TF 2, but I'm not sure.

**Comment by w19787** [comment]
> I haven't met this issue before and I'm not familiar with TF 2.0. Maybe the GPU specification doesn't work properly for TF 2, but I'm not sure.

got it. thanks!

**Comment by Shubham0209** [comment]
@w19787 @zsyzzsoft how can i get these graphs?
```
*Feb26-0245*  2021-02-25 19:46:31 Steps 10, Total time 2.75, data 0.23%. Loss 1.466e+01 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:46:58 Steps 20, Total time 2.71, data 0.24%. Loss 1.158e+01 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:47:25 Steps 30, Total time 2.72, data 0.23%. Loss 8.180e+00 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:47:53 Steps 40, Total time 2.68, data 0.23%. Loss 3.553e+00 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:48:20 Steps 50, Total time 2.74, data 0.23%. Loss 6.937e+00 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:48:48 Steps 60, Total time 2.74, data 0.23%. Loss 4.769e+00 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:49:15 Steps 70, Total time 2.71, data 0.24%. Loss 4.211e+00 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:49:42 Steps 80, Total time 2.73, data 0.24%. Loss 4.451e+00 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:50:09 Steps 90, Total time 2.70, data 0.23%. Loss 2.577e+00 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:50:37 Steps 100, Total time 2.72, data 0.24%. Loss 4.093e+00 lr 1.000e-04
Step 100, validation failed!
*Feb26-0245*  2021-02-25 19:51:04 Steps 110, Total time 2.69, data 0.23%. Loss 3.100e+00 lr 1.000e-04
*Feb26-0245*  2021-02-25 19:51:31 Steps 120, Total time 2.72, data 0.23%. Loss 2.902e+00 lr 1.000e-04
```

Why does it say, validation failed?
PS: I am training the model on my own dataset.
