### ISSUE TITLE
About img augmentation

### ISSUE THREAD

**Issue by w19787** [microsoft/Recursive-Cascaded-Networks#29]
there is img augmentation for moving image. Is it ok to apply same augmentation to the fixed image? I am asking this question since in my case, the dataset is much smaller, if there is no concern, I will try to add augmentation for both images.

![image](https://user-images.githubusercontent.com/731496/84758382-f925ac00-aff7-11ea-899d-84762af5520f.png)

**Comment by zsyzzsoft** [comment]
Yes, but should be careful about how the point1 will be augmented along with the fixed image. An inverse field should be computed.

**Comment by w19787** [comment]
> Yes, but should be careful about how the point1 will be augmented along with the fixed image. An inverse field should be computed.

i am not sure i understand what you say. if i apply same code as follows to fixed image(img1), what will be problem?

```python
augImg1 = augmentation(preprocessedImg1)
augSeg1 = augmentation(seg1)
augPt1 = augmenetation_pts(point1)
```

**Comment by zsyzzsoft** [comment]
Sorry I was wrong that here we don't have a flow to worry about. This seems very OK!

**Comment by w19787** [comment]
> Sorry I was wrong that here we don't have a flow to worry about. This seems very OK!

thanks for kind confirmation!
