### ISSUE TITLE
LPBA segmentation ground truth

### ISSUE THREAD

**Issue by MingR-Ma** [microsoft/Recursive-Cascaded-Networks#31]
Thanks for your work. I'm using your dataset to train my model ,  I want to use LPBA to evaluate my model , but I can't find where the LPBA ground truth is.  Would you provide the LPBA ground truth?

**Comment by zsyzzsoft** [comment]
We have instructions on how to evaluate on LPBA (see README):

Similarly, to evaluate the pretrained 10-cascade VTN (for brain) on the LPBA dataset:
python eval.py -c weights/VTN-10-brain -g YOUR_GPU_DEVICES

Replace "weights/VTN-10-brain" by the path of your own checkpoint to evaluate it.
