### ISSUE TITLE
How to get moving image.

### ISSUE THREAD

**Issue by CGC1031** [microsoft/Recursive-Cascaded-Networks#33]
Thank you for your patient reply before.Your advice is helpful to me.  I have successfully get the real_flow, warped_moving and image_fixed pictures. Through add **keys = ['real_flow', 'image_fixed', 'warped_moving']** .
For the purpose of getting moving image, following the previous method, I attempted to  add the following key words to keys. **['image_moving'] / ['img_moving'] / ['moving']** . But they are all failed.
![QQ图片20200702184725](https://user-images.githubusercontent.com/53649087/86349949-7e65bd80-bc94-11ea-90a2-55a1f7eb1a0d.png)
Prompt us for keyword error['img_moving'].
1、Can you tell me what the key words correspond to the moving image？
2、Or how do you get moving images？Can you give me some ideas？
Looking forward to your reply!

**Comment by zsyzzsoft** [comment]
Please also add a key here, e.g., 'img_moving': img2, at https://github.com/microsoft/Recursive-Cascaded-Networks/blob/0709490fe010e4acc6357990d1d871c170e3ef31/network/recursive_cascaded_networks.py#L176

**Comment by CGC1031** [comment]
Thank you for your reply. I have achieved it successfully. Thanks again.

**Comment by Hoodini-Gzj** [comment]
您好，请问是把eval.py中keys = ['pt_mask', 'landmark_dists', 'jaccs', 'dices', 'jacobian_det', ]替换为keys = ['real_flow', 'image_fixed', 'warped_moving']就可以了吗？还需要修改其他地方吗？

**Comment by Hoodini-Gzj** [comment]
期待您的回复。

**Comment by CGC1031** [comment]
尊敬的赵博士您好！&nbsp; &nbsp; &nbsp;我研究您“Recursive cascaded networks for unsupervised medical image registration”三年了，并在您的工作基础上做了一些研究作为自己的毕设。最近毕业论文的审核老师提出一个疑问，我自己也难以解答，所以冒昧致信向您求教，还望赵博士帮我解解疑惑。
&nbsp; &nbsp; &nbsp;下图中仿射子网络Affine和形变子网络Dense您分别用两个损失函数来进行约束，我想请问一个网络训练为什么会有两个损失函数呢？
假设一：您是不是先用仿射配准子网络的损失函数loss1训练好仿射配准网络的12个形变参数，然后将其固定；再用形变配准子网络的损失函数loss2去训练形变网络的参数。总之就是训练时只有一个loss在起作用，Affine是一个部分，后面的所有形变网络是一个部分，分开训练的。
假设二：loss1指导Affine训练，loss2指导Dense训练，但是二者是同步的，一直训练到结束。整个训练过程中，两个loss同时工作，同时指导Affine和Dense网络参数地不断优化（我也不知道卷积神经网络是否可以同时被两个损失函数所指导？）
&nbsp; &nbsp; &nbsp;非常期待您回复，感谢您！

**Comment by zsyzzsoft** [comment]
The whole network can optimize multiple objectives simultaneously.
