### ISSUE TITLE
Is there Warping Operation available for Ubuntu versions

### ISSUE THREAD

**Issue by luoyi1hao** [microsoft/Recursive-Cascaded-Networks#38]
Using the option fast_reconstruction under Ubuntu's TensorFlow1.4.1 environment, I experienced the following error：
AttributeError: module 'tensorflow.python.user_ops.user_ops' has no attribute 'reconstruction'

Thank you very much for your help

**Comment by zsyzzsoft** [comment]
The custom reconstruction op does not have Ubuntu supported now. Please disable this option instead.
