### ISSUE TITLE
do you have shown results of deformable registration excluding affine network in your paper?

### ISSUE THREAD

**Issue by Dongshengjiang** [microsoft/Recursive-Cascaded-Networks#4]
hello, I am confused by the word in your ICCV paper:"Our 3-cascade VTN (in Table 2) already outperforms VTN (ADDD) (in Table 1) although they have similar network architectures". Is that mean the Table 2  3-cascade VTN is the results of only use recursive deformable net excluding affine net?

**Comment by zsyzzsoft** [comment]
The result is including the affine cascade. The only difference is that the similarity loss is only drawn on the last warped image, in contrast to VTN (ADDD).

**Comment by Dongshengjiang** [comment]
Thanks for your timely reply. By the way, does the preprocess image is not rigid aligned? traditionally, if the image is rigid aligned, and you add some B-spline deformations, then only deformable registration is necessary.

**Comment by zsyzzsoft** [comment]
We did not preprocess the images to be rigidly aligned (which should be very slow using traditional methods). VTN proves that the end-to-end affine network performs even better.
