### ISSUE TITLE
GPU memery needed for training

### ISSUE THREAD

**Issue by haoyayuzzz** [microsoft/Recursive-Cascaded-Networks#41]
Thanks for sharing your code! I want to know the GPU memery needed during training. Because I always suffered the error about resource-exhaused. If I set the batchsize = 1 during traning in liver case, is a 12GB GPU enough to train VTN-10 model?

**Comment by zsyzzsoft** [comment]
I'm not sure as we were using our custom warping operation as explained [here](https://github.com/microsoft/Recursive-Cascaded-Networks#built-in-warping-operation-with-tensorflow), and a 12GB GPU is enough in that case.

**Comment by haoyayuzzz** [comment]
Thanks for your reply. To my understanding, custom warping operation is not available for Ubuntu version, so I might try something else.
