### ISSUE TITLE
LPBA Dice score

### ISSUE THREAD

**Issue by Algolzw** [microsoft/Recursive-Cascaded-Networks#42]
Hello, the code to calculate Dice simply uses "eg1 > 128 and seg2 > 128" (in function 'mask_metrics'), but the LPBA dataset has 56 segmented anatomical structures. How could I calculate the Dice for LPBA?

**Comment by zsyzzsoft** [comment]
See [these lines](https://github.com/microsoft/Recursive-Cascaded-Networks/blob/0709490fe010e4acc6357990d1d871c170e3ef31/network/recursive_cascaded_networks.py#L152-L174) for the evaluation code on LPBA.
