### ISSUE TITLE
Convert to h5 format

### ISSUE THREAD

**Issue by Shubham0209** [microsoft/Recursive-Cascaded-Networks#44]
Hello, @zsyzzsoft 
 
Thank you so much for this wonderful work on image registration.
I am new to this field I was able to successfully run your model/code on your dataset. Actually, I have my own dataset with a folder containing image pairs i.e moving and fixed in .nii format eg: fix_img.nii.gz and mov_img.nii.gz. 

Can you please guide me on how to convert them into h5 format so that I can use my dataset to train on your model?

Thanks in advance!!

**Comment by zsyzzsoft** [comment]
The first step is to preprocess those raw images into image crops. For example, we provide a preprocessing pipeline for liver CT scans in [demo.py](https://github.com/microsoft/Recursive-Cascaded-Networks/blob/master/demo.py). The second step is to save those preprocessed image crops into an h5 file. You may look into and follow the format of our provided datasets using e.g. h5py.

**Comment by Shubham0209** [comment]
The problem is after pre-processing while training the dataset the code any two random images for registration, but I don't want it that way, I want the code to take pair of moving and fixed images. Can you please suggest the edits do I have to make into the code and where?

**Comment by zsyzzsoft** [comment]
You can pass paired=True to the Dataset object. It will group every two adjacent items in the json file as a pair.

**Comment by Shubham0209** [comment]
So I have created the .h5 file which contains single dataset named imgs_trains( all training images being converted into numpy array). And when I try to run train.py I get the following error

```
  File "train.py", line 242, in <module>
    main()
  File "train.py", line 113, in main
    dataset = Dataset(args.dataset, **data_args)
  File "C:\Users\shubh\Desktop\test\data_util\liver.py", line 65, in __init__
    self.subset[k][entry] = self.files[entry]
  File "C:\Users\shubh\Desktop\test\data_util\liver.py", line 41, in __getitem__
    ret = self.files[key[:p]][key[p+1:]]
  File "C:\Users\shubh\Desktop\test\data_util\liver.py", line 28, in __getitem__
    data[k] = group[k]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\shubh\anaconda3\envs\myenv\lib\site-packages\h5py\_hl\dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "C:\Users\shubh\anaconda3\envs\myenv\lib\site-packages\h5py\_hl\selections.py", line 72, in select
    sel[arg]
  File "C:\Users\shubh\anaconda3\envs\myenv\lib\site-packages\h5py\_hl\selections.py", line 212, in __getitem__
    raise TypeError("PointSelection __getitem__ only works with bool arrays")
TypeError: PointSelection __getitem__ only works with bool arrays
```
After reviewing the .h5 files provided by I saw that they had format like this

```
2017_02_aftergas
<HDF5 group "/2017_02_aftergas" (2 members)>
2017_02_pregas
<HDF5 group "/2017_02_pregas" (2 members)>
2017_03_aftergas
<HDF5 group "/2017_03_aftergas" (2 members)>
.
.
.
.
```

But my .h5 has fomat like this 
```
imgs_train
<HDF5 dataset "imgs_train": shape (14, 288, 288, 96), type "<f4">
```
Could this be the problem? Would it be possible for you to share the code on how you transformed images into .h5 file so that the hierarchy is mainted?

Please help!!!
