### ISSUE TITLE
Questions about Datasets

### ISSUE THREAD

**Issue by CGC1031** [microsoft/Recursive-Cascaded-Networks#45]
These are some questions about your datasets that I believe will answer many people's questions about datasets. Thank you for your work and I am looking forward to your reply. I am a loyal fan of your work.

1. Q1:

![SLIVER](https://user-images.githubusercontent.com/53649087/106106349-5da90c00-6180-11eb-8fa0-65ea349468de.png)
Figure 1 is the test file of **SILVER**. 
Could you please tell me whether **yan_x10** and **yan_x11** are from the same person's liver part or the liver part of different people?
In other words, does **yan_x** represent liver part of the same person at different times or images of different people's livers?

2. Q2：

![L](https://user-images.githubusercontent.com/53649087/106107055-65b57b80-6181-11eb-8a13-7739086486f4.png)
![lITS](https://user-images.githubusercontent.com/53649087/106107061-66e6a880-6181-11eb-8145-e7b7bd3f20bf.png)
Similar to the first question, in figure2，I want to figure out **lits/0**, **lits/1**, **lits2**...Are they images of different people's livers?
You wrote in your paper that the **LITs** contained 131scans, does it mean that they came from 131 images of livers of the different person, rather than 131 images of the same person at different moments. 

3. Q3:

![LSPIG](https://user-images.githubusercontent.com/53649087/106108006-a2ce3d80-6182-11eb-8672-5ded82ea8cb1.png)
Through reading your paper, I understand that the **LSPIG** data set contains liver images from `17 different pigs`, which are registered in pairs before and during surgery. Do I understand you correctly?

4. Q4：

Thank you for reading here, the last question.
For the training set **MSD**, it contains four kinds of liver lesion images, such as Hepatic animal and Pancreas Tumours. When you select two images for training, do you select two images from the same lesion image for concatenate ? Or will one of the two different lesion areas be selected and concatenate into the network? 
In other words, I would like to know how you select a pair of registration images in the MSD dataset for training.

**Comment by zsyzzsoft** [comment]
Q1&Q2: These scans are from different people.
Q3: Correct.
Q4: All pairs (can be from different kinds) are randomly selected for training.

**Comment by CGC1031** [comment]
Thank you for replying so quickly.
During the training stage, datasets randomly selected from different kinds, I think it's understandable. Because in fact, the training process is the process of extracting features.
During the testing stage, for **LSPIG** data, registration for preoperative and intraoperative registration of the same person will have a good application in surgical navigation. It's OK.
However, I have been puzzled by the choice of liver images from different people for the registration of the **SILVER** and **LITS** datasets. Because everyone's physical condition is different. Is there any application for scene registration by using images of two different individuals?

**Comment by zsyzzsoft** [comment]
I can say there are applications, though not as many as intra-subject registration, e.g. when you want to compare someone's scan with a healthy one or a standard one.

**Comment by CGC1031** [comment]
Thank you for your prompt reply. I have understood.

**Comment by CGC1031** [comment]
Hello! There is another question. I can get all the 2D slices after registration, but the visual effect is not good. How can I get the 3D image in the article of VTN? How do you do 3D reconstruction? Looking forward to your suggestions
![3d](https://user-images.githubusercontent.com/53649087/106350819-ce802d80-6312-11eb-9f13-5f8a8bff7090.png)

**Comment by zsyzzsoft** [comment]
These are generated by some code, but I don't have the code now.

**Comment by CGC1031** [comment]
OK，I tried some methods, but they didn't look good.  Thank you very much.
