### ISSUE TITLE
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value gaffdfrm/deform_stem_1/conv3_1/b

### ISSUE THREAD

**Issue by YMBrianHung** [microsoft/Recursive-Cascaded-Networks#5]
When I run the command line:
python eval.py -c weights/VTN-10-liver -g 3 -v lits
I got the error: FailedPreconditionError (see above for traceback): Attempting to use uninitialized value gaffdfrm/deform_stem_1/conv3_1/b
How can I deal with this problem?

**Comment by zsyzzsoft** [comment]
I cannot replicate the error using my Tensorflow versions (both 1.4 and 1.13). Maybe run the initializer before loading the checkpoint could resolve this problem. Update the code and try it again.

**Comment by zsyzzsoft** [comment]
I'm closing this issue. Feel free to reopen it if there is still any problem.
