### ISSUE TITLE
请教VTN中的仿射变换子网络的损失函数

### ISSUE THREAD

**Issue by maxwellTF** [microsoft/Recursive-Cascaded-Networks#51]
大佬你好，请问VTN中求仿射变换12参数（我做2D影像所以是6参数），这部分的损失函数，是包括论文中提到的四部分吗？相似性、平滑、矩阵的正交性和行列式？各损失函数推荐的比例系数是怎样的？感谢解答！

**Comment by zsyzzsoft** [comment]
The weights of losses are listed in Table I in the VTN paper.
