### ISSUE TITLE
when I set aug = 'identity' or aug is None, the validation results using your model is exeactly the same

### ISSUE THREAD

**Issue by Dongshengjiang** [microsoft/Recursive-Cascaded-Networks#6]
when I set aug = 'identity' or aug is None, the validation results using your model is exeactly the same. is the augmentation not work rightly?

**Comment by zsyzzsoft** [comment]
The augmentation only affects the training phase. We're not doing augmentation in validation.

**Comment by Dongshengjiang** [comment]
But I indeed found that the below code is still running in validate phase, and I did not find any code distincting training and validating phase.

"control_fields = transform.sample_power(
                -0.4, 0.4, 3, tf.stack([bs, 5, 5, 5, 3])) * (np.array(imgs) // 4)
            augFlow = transform.free_form_fields(imgs, control_fields)"

**Comment by zsyzzsoft** [comment]
Yes, it's expected to run once when building TF graph, but the actual operation is conditioning on the training mode (see framework.py, line 57 and 67).

**Comment by Dongshengjiang** [comment]
o, I see. Thank you very much for your help!
