### ISSUE TITLE
about how to wrap a label

### ISSUE THREAD

**Issue by YuqingCai0316** [microsoft/Recursive-Cascaded-Networks#62]
Dear developer，
        I have successfully run demo.py to register the liver. I am confused that if I have a label, which is an array of 0 and 1, how can I apply the predicted deformation field to this label?
        Thank you in advance, I am looking forward to receive your response.

**Comment by zsyzzsoft** [comment]
I think it is more convenient if to write some custom code. Existing code only applies to structured datasets.

**Comment by YuqingCai0316** [comment]
thank you! I might be able to do it myself

**Comment by CGC1031** [comment]
你好，我可以和你交流几个问题吗？我做这个级联的项目也做了很久了，如果可以交流麻烦加QQ244040023谢谢啦
