### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by YuqingCai0316** [microsoft/Recursive-Cascaded-Networks#63]
![1635390563(1)](https://user-images.githubusercontent.com/50909355/139179565-95112660-f93b-44bb-9019-29c5817d7724.png)
I want to know what is the purpose of defining seg1 and seg2? Seems to be useless later ...

**Comment by zsyzzsoft** [comment]
They are the annotated segmentation masks of img1 and img2. They are useful for Dice score evaluation.

**Comment by YuqingCai0316** [comment]
Are these two masks manually marked on img1 and img2？
Or, One of them is a mask that was predicted by the neural network？

**Comment by zsyzzsoft** [comment]
Yes, both of them are manually annotated.
