### ISSUE TITLE
Application for large histology images

### ISSUE THREAD

**Issue by Borda** [microsoft/Recursive-Cascaded-Networks#7]
Hello, I came across to this nice project and it seems quite powerful.
Have you experienced to use it also for large histology images, talking about images with 10k pixels in diagonal and more? Would you be interested in participating in [AHNIR challenge](https://anhir.grand-challenge.org/) or include your method into [BIRL framework](https://borda.github.io/BIRL/)?

**Comment by zsyzzsoft** [comment]
Nice challenge! It reveals a major problem of the similarity-based algorithms and we might have a deeper investigation in the future work.

**Comment by CGC1031** [comment]
Dear author, I am a graduate student of soochow university. Your research achievements are very excellent. Thank you for your contribution.
I very want to realize the work you have done, but run **eval. py** encountered the following error: **'ImportError: always import a name' dense_features' from 'tensorflow. Python. Feature_column'.**
I have tried many methods but failed. Do you have any method to solve it?Looking forward to your reply.Thank you very much.

**Comment by zsyzzsoft** [comment]
> I very want to realize the work you have done, but run **eval. py** encountered the following error: **'ImportError: always import a name' dense_features' from 'tensorflow. Python. Feature_column'.**

Looks like you have an incorrect Tensorflow version. Feel free to open a new issue --- I haven't received a notification for this comment.

**Comment by CGC1031** [comment]
Thank you very much,I have found the&nbsp;correct Tensorflow version and solved this problom.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zsyzzsoft"<notifications@github.com&gt;; 
发送时间: 2020年4月3日(星期五) 凌晨0:35
收件人: "microsoft/Recursive-Cascaded-Networks"<Recursive-Cascaded-Networks@noreply.github.com&gt;; 
抄送: "蔡港成"<244040023@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [microsoft/Recursive-Cascaded-Networks] Application for large histology images (#7)





  
I very want to realize the work you have done, but run eval. py encountered the following error: 'ImportError: always import a name' dense_features' from 'tensorflow. Python. Feature_column'.
 
Looks like you've an incorrect Tensorflow version. Feel free to open a new issue --- I haven't received a notification for this comment.
