### ISSUE TITLE
what's the format of the deformation field?

### ISSUE THREAD

**Issue by mvoofan** [microsoft/Recursive-Cascaded-Networks#8]
Thanks for you kindly sharing your codes. It is very nice work and it canbe excuted directly.

I get the deformation field (128*128*128*3 matrix) by adding "real_flow" in the variable "keys" (in eval.py).  However, I cannot get the right warped image using the floating image and the deformation field (I used the SimpleITK.Warp function). I wonder whether you can added some explanation to the deformation field.

**Comment by mvoofan** [comment]
Sorry. Maybe I use the wrong displacement variable in SimpleITK.

**Comment by Hoodini-Gzj** [comment]
> 
> 
> Thanks for you kindly sharing your codes. It is very nice work and it canbe excuted directly.
> 
> I get the deformation field (128_128_128*3 matrix) by adding "real_flow" in the variable "keys" (in eval.py). However, I cannot get the right warped image using the floating image and the deformation field (I used the SimpleITK.Warp function). I wonder whether you can added some explanation to the deformation field.

How do you get the deformation field? Could you tell me more about it.Looking forward to your reply.
I am a newbie, can you share your part of the code?

**Comment by mvoofan** [comment]
> > Thanks for you kindly sharing your codes. It is very nice work and it canbe excuted directly.
> > I get the deformation field (128_128_128*3 matrix) by adding "real_flow" in the variable "keys" (in eval.py). However, I cannot get the right warped image using the floating image and the deformation field (I used the SimpleITK.Warp function). I wonder whether you can added some explanation to the deformation field.
> 
> How do you get the deformation field? Could you tell me more about it.Looking forward to your reply. I am a newbie, can you share your part of the code?

Just  add "real_flow" in the variable "keys" (in eval.py), then u can get a dict varibale return (maybe named "results").

**Comment by Hoodini-Gzj** [comment]
> > > Thanks for you kindly sharing your codes. It is very nice work and it canbe excuted directly.
> > > I get the deformation field (128_128_128*3 matrix) by adding "real_flow" in the variable "keys" (in eval.py). However, I cannot get the right warped image using the floating image and the deformation field (I used the SimpleITK.Warp function). I wonder whether you can added some explanation to the deformation field.
> > 
> > 
> > How do you get the deformation field? Could you tell me more about it.Looking forward to your reply. I am a newbie, can you share your part of the code?
> 
> Just add "real_flow" in the variable "keys" (in eval.py), then u can get a dict varibale return (maybe named "results").

Thank u for ur reply. I have successfully obtained the result according to ur suggestion. Wish everything goes well with your work! :)
