### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by rickardcronholm** [microsoft/Recursive-Cascaded-Networks#9]
Could you provide details regarding dependencies and versions, preferably in a requirements.txt file from `pip freeze`?

**Comment by zsyzzsoft** [comment]
Sure, I'll post it here:

h5py==2.8.0
itk==4.13.1.post1
Keras==2.2.2
numpy==1.17.2+mkl
numpy-stl==2.7.0
PyYAML==3.13
scikit-image==0.14.2
scipy==1.1.0
SimpleITK==1.1.0
tensorflow-gpu==1.4.1
tensorflow-tensorboard==0.4.0
tflearn==0.3.2
tqdm==4.25.0
